name: End-to-End Tests
on:
  push:
    branches: [ '*' ]

jobs:
  build-and-test:
    name: Install docker and Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
          docker-compose --version
      - name: Build docker and Run E2E Tests
        run: ./e2e_tests/run-e2e-tests.sh